services:
  datoso:
    build: .
    volumes:
      - /datoso:/datoso
      - /datRoot:/datRoot
      - /download:/download
    environment:
      DATOSO.DATOSOPATH: "/datoso"
      DATOSO.DATPATH: "/datRoot"
      DATOSO.DOWNLOADPATH: "/download"
      DATOSO.DATABASEFILE: "datoso.json"
      FBNEO.FETCHFULL: "true"
      FBNEO.FETCHLIGHT: "false"
      UPDATE_URLS.GOOGLESHEETURL: "https://sheets.googleapis.com/v4/spreadsheets/1LgU7uJOtVOUWYkdoaeSbux41biFwpbzVosm98bgdN3k/values/Systems!A1:E300?key=AIzaSyA2pmHY5FVJFEjauoE8kKV6-UcCM4Tfk44"
      DOWNLOAD.PREFFERDOWNLOADUTILITY: "wget"
      IMPORT.IGNOREREGEX: ".*(?:MAME|FruitMachines|Fruit Machine|TeknoParrotGames|PleasureDome|fixDat).*"
      LOG.LOGGING: "true"
      LOG.LOGLEVEL: "INFO"
      LOG.LOGFILE: "datoso.log"
      PREFIXES.ARCADE: "Arcade"
      PREFIXES.AUDIO: "Other/Audio"
      PREFIXES.BOOK: "Other/Book"
      PREFIXES.CALCULATOR: "Other/Calculator"
      PREFIXES.COMPUTER: "Computer"
      PREFIXES.CONSOLE: "Consoles"
      PREFIXES.HANDHELD: "Consoles"
      PREFIXES.PDA: "Mobile"
      PREFIXES.PHONE: "Mobile"
      PREFIXES.SOURCECODE: "Other/Source Code"
      PREFIXES.VIDEO: "Other/Video"
      PREFIXES.MOBILE: "Mobile"
      PREFIXES.MANUALS: "Other/Manuals"
      PREFIXES.BIOSIMAGES: "Other/BIOS Images"

